### ISSUE TITLE
Замечания по Prime Numbers

### ISSUE THREAD

**Issue by alexey-malov** [eligantRU/oop#12]
- [x] Не выполнено требование задания:

> С ее использованием разработайте программу, выводящую в стандартный поток вывода элементы множества простых чисел, не превышающие значения, переданного приложению через обязательный параметр командной строки.

**Comment by alexey-malov** [comment]
- [x] Под верхней границей подразумевается то число, БОЛЬШЕ которого простые числа выодить не надо. Сама верхняя граница входит в диапазон: [0, upperBound]

**Comment by alexey-malov** [comment]
- [x] В программе неопределенное поведение - выход за пределы решета

**Comment by alexey-malov** [comment]
- [x] Реализацию лучше разместить в .cpp файле

**Comment by eligantRU** [comment]
Исправлено всё, за исключением перемещения реализации в *.cpp : f601d6597e00c9de9e739e871f59a832e77f7541

**Comment by alexey-malov** [comment]
``` c++
    for (unsigned i = 2; i <= sqrt(upperBound); ++i)
    {
        for (unsigned j = 2 * i; j <= upperBound; j += i)
        {
            nums[j] = false;
        }
    }
```
- [x] Лучше проверить, что квадрат i меньше upperBound, а еще лучше, что upperBound / i <= i, тогда не будет переполнения

**Comment by alexey-malov** [comment]
- [x] Внутренний цикл можно начинать с квадрата числа

**Comment by alexey-malov** [comment]
- [x] Если число из внешнего цикла уже не является простым, то вычеркиват кратные ему не имеет смысла, т.к. они уже вычеркнуты. Сравните прирост скорости.

**Comment by alexey-malov** [comment]
- [x] Воспользуйся тем, что 2 - единственное четное число из простых.

**Comment by alexey-malov** [comment]
- [x] воспользуйся тем, что вставка происходит всегда в конец множества. В этом случае emplace_hint или insert с подсказкой избавят от необходимости выполнять поиск позиции вставки

**Comment by alexey-malov** [comment]
итого - достичь трехкратного ускорения!

**Comment by eligantRU** [comment]
Исправлено dfa446d8c0c1cebc52f7bd352ecbfd0045376fbc

**Comment by alexey-malov** [comment]
принято
