### ISSUE TITLE
Замечания по программе Replace

### ISSUE THREAD

**Issue by alexey-malov** [eligantRU/oop#3]
- [x] Реализовать линейную сложность в зависимости от размера входной строки
- [x] Выделить функцию, выполняющую замену всех вхождений искомой строки во входной
- [x] Обеспечить работу в 64 битной конфигурации
- [x] Тесты должны запускаться во всех конфигурациях
- [x] Не используйте exit. Используйте return
- [x] Напишите скрипт для тестирования

**Comment by eligantRU** [comment]
Use CALL in *.bat files & IF NOT ERRORLEVEL 1

**Comment by eligantRU** [comment]
Исправлено

**Comment by alexey-malov** [comment]
``` c++
std::string FindAndReplace(const std::string & inputStr, const std::string & searchStr, const std::string & replaceStr)
{
    auto currentStr = inputStr;

    auto it = currentStr.find(searchStr);
    while (it != std::string::npos)
    {
        currentStr.replace(it, searchStr.length(), replaceStr);
        it = currentStr.find(searchStr, it + replaceStr.length());
    }
    return currentStr;
}
```
- [x] Лучше не использовать имя it для хранения позиции в строках и векторах. Итераторы становятся невалидными при изменении длины строки в большую сторону (итератор - аналог указателя). Лучше использовать pos

**Comment by alexey-malov** [comment]
- [x] Не использовать абсолютные пути в тестах. Нормально ожидать, что fc.exe будет доступна через PATH.

**Comment by eligantRU** [comment]
Абсолютные пути исправлены во всех проектах, it переименован в pos

**Comment by eligantRU** [comment]
Исправлена сложность алгоритма с O(n^2) на O(n) [https://github.com/eligantRU/oop/commit/a86e24652161b1b5bf664d84c056c6eb2301f7ed]

**Comment by alexey-malov** [comment]
``` c++
std::string FindAndReplace(const std::string & inputStr, const std::string & searchStr, const std::string & replaceStr)
{
    std::string result;
    size_t initialPos = 0;

    auto pos = inputStr.find(searchStr);
    while (pos != std::string::npos)
    {
        result.append(inputStr, initialPos, pos - initialPos);
        result.append(replaceStr);
        initialPos = pos + searchStr.length();
        pos = inputStr.find(searchStr, initialPos);
    }
    result.append(inputStr, initialPos);
    return result;
}
```

Рекомендации:
- [x] использовать for (-1 find)
- [x] использовать reserve с размером равным исходной строке

**Comment by alexey-malov** [comment]
- [x] Выделить функцию замены, принимающую имена файлов

**Comment by eligantRU** [comment]
Исправлено

**Comment by alexey-malov** [comment]
``` c++
    for (auto pos = inputStr.find(searchStr); pos != std::string::npos; pos = inputStr.find(searchStr, initialPos))
    {
        result.append(inputStr, initialPos, pos - initialPos);
        result.append(replaceStr);
        initialPos = pos + searchStr.length();
    }
```
- [x] перенести find во второй аргумент for ( ... ; (pos = str.find()) != string::npos; ...)

**Comment by eligantRU** [comment]
Исправлено: 7e10ac9ebb9f0ab8e15c4b4240a563b65c2e6108

**Comment by alexey-malov** [comment]
принято
